server:
  address: 192.168.1.119
  port: 5201
  context-path: /note1
  undertow:
    accesslog:
      enabled: false
datasource:
  type: mysql
  url: jdbc:mysql://192.168.1.120:3306/loveshare?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&oldsyntax=true
  username: dba
  password: 123456
  driver: com.mysql.jdbc.Driver
  initialSize: 8
  minIdle: 8
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 1800000
  maxEvictableIdleTimeMillis: 25200000
  removeAbandoned: true
  removeAbandonedTimeoutMillis: 300000
  timeBetweenConnectErrorMillis: 30000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: true
  poolPreparedStatements: true
  maxOpenPreparedStatements: 15
  logAbandoned: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall,log4j
  connectionProperties: stat.mergeSql=true;stat.slowSqlMillis=5000
  loginUsername: admin
  loginPassword: 123456
  resetEnable: false
  allow: 192.168.1.119/165/175
  deny: 192.168.10.119
mybatis:
  mapper-locations: classpath*:me/loveshare/note1/data/xml/*Mapper.xml
  type-aliases-package: me.loveshare.note1.data.entity.dbo
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30
swagger:
  api: "me.loveshare.note1.api"
  title: "我爱分享"
  description: "Spring boot学习笔记1，RESTful API 接口文档说明"
  version: 1.0.0
  author: Tony Tian
  gmt: 2017-08-01