server:
  address: 192.168.1.104
  port: 5204
  context-path: /note4
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
https:
  port: 7204
  keystore-password: 123456
#  keystore-file: D:/rsakey/loveshare.keystore #Windows
  keystore-file: /Users/tony_tian/develop/keys/loveshare.keystore  #Mac
spring:
#  resources:  # swagger html: 404
#    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    charset: UTF-8
    cache: false
    prefer-file-system-access: true
    content-type: text/html
    enabled: true
    suffix: .html
  messages:
    basename: ValidationMessages
swagger:
  api: "me.loveshare.web.api"
  title: "数据测试接口文档"
  description: "数据测试接口文档，RESTful API 接口文档说明"
  version: "1.0.0"
  author: "Tony_Tian"
  gmt: "2017-11-27"
endpoints: # 安全地停止SpringBoot应用服务 (依赖jar：spring-boot-starter-actuator)
  shutdown:
    enabled: true #启用shutdown, curl -X POST http://host:port/shutdown
    sensitive: false #禁用密码验证